---
- src: franklinkim.timezone
  version: '1.0.0'
- src: angstwad.docker_ubuntu
  version: 'v3.4.5'
- src: franklinkim.git
  version: '1.2.2'
- src: franklinkim.environment
  version: '1.3.0'
- src: cmprescott.chrome
  version: '0.2.4'
- src: geerlingguy.nodejs
  version: '4.1.2'
- src: tersmitten.locales
  version: 'v1.0.17'
- src: gantsign.apt
  version: '1.2.0'
- src: gantsign.atom
  version: '1.4.0'
- src: gantsign.atom-packages
  version: '1.1.0'
- src: gantsign.audio
  version: '1.2.0'
- src: https://github.com/gantsign/ansible-role-command-line-tools/archive/1.3.0.tar.gz
  name: gantsign.command-line-tools
- src: gantsign.default-web-browser
  version: '3.1.0'
- src: gantsign.gnome-proxy
  version: '1.1.0'
- src: gantsign.golang
  version: '1.3.2'
- src: gantsign.inotify
  version: '1.1.0'
- src: gantsign.intellij
- src: gantsign.intellij-plugins
  version: '1.3.3'
- src: gantsign.java
  version: '4.7.0'
- src: gantsign.keyboard
  version: '1.3.0'
- src: gantsign.kubernetes
  version: '1.1.0'
- src: gantsign.lightdm
  version: 'v2.1.0'
- src: gantsign.maven
  version: '4.0.0'
- src: gantsign.maven-notifier
  version: '2.4.0'
- src: gantsign.molecule
  version: '4.0.0'
- src: gantsign.postman
  version: '2.1.0'
- src: gantsign.oh-my-zsh
  version: '1.2.1'
- src: gantsign.pin-to-launcher
  version: '2.1.0'
- src: gantsign.terminator
  version: '1.1.0'
- src: https://github.com/gantsign/ansible-role-unison/archive/1.3.0.tar.gz
  name: gantsign.unison
- src: gantsign.visual-studio-code
- src: gantsign.visual-studio-code-extensions
  version: '1.4.0'
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/2.3.0.tar.gz
  name: gantsign.xdesktop
- src: gantsign.zram-config
  version: '1.2.0'
#Rove, added:
- src: arknoll.firefox
